#!/bin/bash

BASEDIR=/sys/devices/system/cpu/cpufreq

if [[ ! -d "${BASEDIR}" ]]; then
    logger "no frequency scaling support detected"
fi

if [[ $# -ge 1 ]]; then
    case "${1}" in
        "-h"|"--help")
            cat <<EOF
Usage

Options:
-h | --help     This help

Commands:
list            Show the currently active governors
EOF
            exit 0
            ;;
        "list")
            for d in "${BASEDIR}"/policy?; do
                cat "${d}/scaling_governor"
            done
            exit 0
            ;;
        *)
            echo "unknown command line option"
            exit 1
            ;;
    esac
fi

logger --priority user.debug "checking power"
for d in $(find /sys/devices -type d -name 'power_supply'); do
    if [[ -f "${d}"/AC/online ]]; then
        ac_online=$(cat "${d}"/AC/online)
    fi
done
if [[ ${ac_online} == "1" ]]; then
    logger --priority user.debug "AC power connected"
    wanted_governor=conservative
elif [[ ${ac_online} == "0" ]]; then
    logger --priority user.debug "AC power disconnected"
    wanted_governor=powersave
else
    logger --priority user.error "can not find power information"
    exit 0
fi

logger --priority user.debug "checking scaling governors"
for d in "${BASEDIR}"/policy?; do
    if [[ -f "${d}"/scaling_governor ]]; then
        governor=$(cat "${d}"/scaling_governor)
        if [[ "${governor}" != "${wanted_governor}" ]]; then
            logger --priority user.debug "updating ${governor} to ${wanted_governor}"
            echo "${wanted_governor}" > "${d}"/scaling_governor
        else
            logger --priority user.debug "governor correctly set to ${governor}"
        fi
    fi
done
